package.json, src/index.coffee, src/logger.subscriber.coffee, src/observers/delay.levels.coffee, src/observers/delay.observer.coffee, src/observers/delay.observer.spec.coffee, src/observers/redis.observer.coffee, src/processor.builder.coffee, src/processor.coffee, src/processors/request.processor.coffee, src/processors/request.processor.spec.coffee, src/services/redis.coffee, src/specHelpers/fixture.coffee, src/specHelpers/redis.observer.mock.coffee
=> Request processors

src/observers/delay.observer.coffee, src/observers/delay.observer.spec.coffee, src/observers/logger.observer.coffee, src/observers/redis.observer.coffee, src/processor.builder.coffee, src/processor.coffee, src/processors/request.processor.coffee, src/sources/queue.source.coffee, src/sources/service.bus.source.coffee, src/sources/unknown.source.coffee, src/specHelpers/fixture.coffee
=> Dequeue count

src/index.coffee, src/observers/deadLetterSucceeded.observer.coffee, src/observers/deadLetterSucceeded.observer.spec.coffee, src/observers/delay.observer.coffee, src/observers/didLastRetry.observer.coffee, src/observers/didLastRetry.observer.spec.coffee, src/observers/redis.observer.coffee, src/processor.builder.coffee, src/sources/queue.source.coffee, src/sources/service.bus.source.coffee, src/sources/unknown.source.coffee, src/specHelpers/fixture.coffee
=> Did last retry

src/processors/request.processor.coffee, src/processors/request.processor.spec.coffee
RequestProcesor(msg => Promise\<T>)
RequestProcessor(msg => T)
=> Request processor may use a promise

README.md, src/processors/job/index.coffee, src/processors/job/job.processor.coffee, src/processors/job/job.processor.spec.coffee, src/processors/job/notification.api.coffee, src/processors/job/notification.api.spec.coffee, src/processors/request.async.processor.coffee
=> Remove duplicate code job processor

src/processors/maxRetries.processor.coffee
=> Add default 0 for dequeueCount on _shouldRetry_

src/index.coffee, src/processors/requestWithRetries.async.processor.coffee
[Finishes #174581494](https://www.pivotaltracker.com/story/show/174581494)
=> Request async with max retries

src/processors/job/job.processor.coffee, src/processors/job/job.processor.spec.coffee
[Finishes #175674340](https://www.pivotaltracker.com/story/show/175674340)
=> Throw nonretyable exception after notify the failure

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, package-lock.json, src/observers/deadLetterSucceeded.observer.coffee, src/observers/didLastRetry.observer.coffee, src/observers/incidentsApi.observer.coffee, src/observers/redis.observer.coffee
[Finishes #175674340](https://www.pivotaltracker.com/story/show/175674340)
=> Support aysnc senders

src/observers/incidentsApi.observer.coffee, src/processors/request.async.processor.coffee, src/senders/async.producteca.sender.coffee, src/senders/index.coffee, src/services/oAuthApi.coffee
[Finishes #176002588](https://www.pivotaltracker.com/story/show/176002588)
Y fixea un bug que hacia que no se manden los mensajes correctamente.
Al nuevo sender se le puede pasar un resourceGetter porque por ejemplo la de channel-importe lo agarra del body. Es un parametro del resource para no meter un breaking
=> Adds async sender

package-lock.json, package.json, src/processors/job/job.processor.coffee, src/processors/job/job.processor.spec.coffee, src/processors/job/notification.api.coffee
[Finishes #ID](https://www.pivotaltracker.com/story/show/ID)
=> Ignore actions for stopped jobs

copyToFunction, package.json, src/processors/job/job.processor.coffee, src/processors/job/job.processor.spec.coffee, src/processors/job/notification.api.coffee, src/processors/job/notification.api.spec.coffee
=> Reintentar notification async

package-lock.json, src/processors/job/notification.api.coffee
[Finishes #4830865817](https://producteca.monday.com/boards/427697446/views/44072200/pulses/4830865817)
=> Recalculo basic token para notificationsApi

package-lock.json, package.json, src/index.coffee, src/observers/monitorCenter.observer.coffee, src/observers/monitoringCenter.observer.coffee
=> Monitor center observer

src/observers/monitoringCenter.observer.coffee
[Finishes #ID](https://www.pivotaltracker.com/story/show/ID)
=> add date to file

src/observers/monitoringCenter.observer.coffee
[Finishes #ID](https://www.pivotaltracker.com/story/show/ID)
=> Monitor enhancements

src/processor.coffee, src/processors/request.processor.coffee
[Finishes #ID](https://www.pivotaltracker.com/story/show/ID)
=> Execution id runner

.github/PULL_REQUEST_TEMPLATE.md, src/processors/job/notification.api.coffee
[Finishes #4968232971](https://producteca.monday.com/boards/427697446/pulses/4968232971)
=> Agrego campo error a los job operation fail request

src/processors/job/notification.api.coffee
[Finishes #4968232971](https://producteca.monday.com/boards/427697446/pulses/4968232971)
=> Meli error type fix

src/observers/monitoringCenter.observer.coffee
=> migrate s3 to firehose

src/observers/monitoringCenter.observer.coffee, src/processors/job/index.coffee, src/processors/job/job.processor.spec.coffee, src/processors/job/notification.api.coffee, src/processors/maxRetries.processor.coffee, src/processors/request.async.processor.coffee, src/senders/async.producteca.sender.coffee, src/senders/meli.sender.coffee, src/senders/producteca.sender.coffee, src/services/oAuthApi.coffee, src/services/userIdTranslator.coffee, src/sources/queue.source.coffee, src/sources/service.bus.source.coffee
=> Meli + Async monitoring center

src/observers/monitoringCenter.observer.coffee
=> fix execution status

src/processors/job/index.coffee, src/processors/job/job.processor.coffee
=> fix executionid jobs

src/observers/monitoringCenter.observer.coffee, src/senders/async.producteca.sender.coffee
=> Add message to payload

src/processor.coffee, src/processors/job/index.coffee, src/processors/job/job.processor.coffee, src/processors/job/job.processor.spec.coffee, src/processors/maxRetries.processor.coffee, src/processors/request.processor.spec.coffee
[Finishes #5838216272](https://producteca.monday.com/boards/427697446/views/44072200/pulses/5838216272)
=> Job processor silent errors

src/processors/job/job.processor.spec.coffee, src/processors/maxRetries.processor.coffee
[Finishes #5838216272](https://producteca.monday.com/boards/427697446/views/44072200/pulses/5838216272)
=> fix: notify silent error as successful

src/observers/monitoringCenter.observer.coffee
[Finishes #6679215003](https://producteca.monday.com/boards/427697446/views/13284263/pulses/6679215003)
=> short azure function timed out error

.github/actions/analyze-release/action.yml, .github/actions/analyze-release/analyze-bump.js, .github/workflows/comment-release.yml, .github/workflows/release.yml, .npmignore, commitlint.config.js, package-lock.json, package.json
[Finishes #9406542447](https://producteca.monday.com/boards/427697446/pulses/9406542447)
=> Automatic release

src/sources/aws.sqs.source.coffee
[Finishes #9393578114](https://producteca.monday.com/boards/427697446/pulses/9393578114)
=> fix: agrego dequeuecount

.github/workflows/release.yml
=> fix(release): download build output

src/processors/maxRetries.processor.coffee
[Finishes #9976521536](https://producteca.monday.com/boards/427697446/pulses/9976521536)
=> feat: agrego timeout para processor en maxretries

commitlint.config.js, package-lock.json, package.json
[Finishes #9496660678](https://producteca.monday.com/boards/8925173817/pulses/9496660678)
=> Linterteca
